/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '2/5/24, 9:05 PM' 
 * Generated by 'u63767787' 
 * Generated on server 'ODAWS01-APSE1-2.ODA.SAS.COM' 
 * Generated on SAS platform 'Linux LIN X64 3.10.0-1062.12.1.el7.x86_64' 
 * Generated on SAS version '9.04.01M7P08062020' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0' 
 * Generated on web client 'https://odamid-apse1-2.oda.sas.com/SASStudio/main?locale=en_US&zone=GMT%252B11%253A00&ticket=ST-71525-H4saNN9JGjMhc05MvDjB-cas' 
 *
 */

ods graphics / reset width=5in height=3in imagemap;

proc sgplot data=SASHELP.CARS;
	title height=14pt "vehicle stats";
	scatter x=Horsepower y=MPG_City / group=Origin 
		markerattrs=(symbol=circlefilled size=12) transparency=0.75;
	xaxis grid;
	yaxis grid;
	keylegend / location=inside;
run;

ods graphics / reset;
title;

