/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '2/5/24, 9:12 PM' 
 * Generated by 'u63767787' 
 * Generated on server 'ODAWS01-APSE1-2.ODA.SAS.COM' 
 * Generated on SAS platform 'Linux LIN X64 3.10.0-1062.12.1.el7.x86_64' 
 * Generated on SAS version '9.04.01M7P08062020' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0' 
 * Generated on web client 'https://odamid-apse1-2.oda.sas.com/SASStudio/main?locale=en_US&zone=GMT%252B11%253A00&ticket=ST-71525-H4saNN9JGjMhc05MvDjB-cas' 
 *
 */

ods graphics / reset width=6in height=4in imagemap;

proc sort data=SASHELP.STOCKS out=_SeriesPlotTaskData;
	by Date;
run;

proc sgplot data=_SeriesPlotTaskData;
	title height=14pt "stock close by month";
	series x=Date y=Close / group=Stock;
	xaxis grid display=(nolabel);
	yaxis grid display=(nolabel);
run;

ods graphics / reset;
title;

proc datasets library=WORK noprint;
	delete _SeriesPlotTaskData;
	run;