/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '2/5/24, 9:27 PM' 
 * Generated by 'u63767787' 
 * Generated on server 'ODAWS01-APSE1-2.ODA.SAS.COM' 
 * Generated on SAS platform 'Linux LIN X64 3.10.0-1062.12.1.el7.x86_64' 
 * Generated on SAS version '9.04.01M7P08062020' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0' 
 * Generated on web client 'https://odamid-apse1-2.oda.sas.com/SASStudio/main?locale=en_US&zone=GMT%252B11%253A00&ticket=ST-71525-H4saNN9JGjMhc05MvDjB-cas' 
 *
 */

/* Compute axis ranges */
proc means data=SASHELP.CARS noprint;
	class Type / order=data;
	var MPG_City MPG_Highway;
	output out=_BarLine_(where=(_type_ > 0)) mean(MPG_City MPG_Highway)=resp1 
		resp2;
run;

/* Compute response min and max values (include 0 in computations) */
data _null_;
	retain respmin 0 respmax 0;
	retain respmin1 0 respmax1 0 respmin2 0 respmax2 0;
	set _BarLine_ end=last;
	respmin1=min(respmin1, resp1);
	respmin2=min(respmin2, resp2);
	respmax1=max(respmax1, resp1);
	respmax2=max(respmax2, resp2);

	if last then
		do;
			call symputx ("respmin1", respmin1);
			call symputx ("respmax1", respmax1);
			call symputx ("respmin2", respmin2);
			call symputx ("respmax2", respmax2);
			call symputx ("respmin", min(respmin1, respmin2));
			call symputx ("respmax", max(respmax1, respmax2));
		end;
run;

/* Define a macro for offset */
%macro offset ();
	%if %sysevalf(&respmin eq 0) %then
		%do;
			offsetmin=0 %end;

	%if %sysevalf(&respmax eq 0) %then
		%do;
			offsetmax=0 %end;
%mend offset;

ods graphics / reset width=6.4in height=4.8in imagemap;

proc sgplot data=SASHELP.CARS nocycleattrs;
	title height=14pt "mean mileage by type";
	vbar Type / response=MPG_City fillattrs=(color=CXa70000) stat=mean;
	vline Type / response=MPG_Highway lineattrs=(thickness=10) stat=mean y2axis;
	xaxis display=(nolabel);
	yaxis grid min=&respmin1 max=&respmax1 %offset();
	y2axis min=&respmin2 max=&respmax2 %offset();
	keylegend / location=outside;
run;

ods graphics / reset;
title;

proc datasets library=WORK noprint;
	delete _BarLine_;
	run;